name: 'Docker'

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  matrix:
    runs-on: ubuntu-latest

    name: 'Matrix'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: 'Load configurations'
        id: configurations
        working-directory: scripts
        run: echo "::set-output name=configurations::$(php configurations.php)"
      
    outputs:
      configurations: ${{ steps.configurations.outputs.configurations }}

  dockerfile:
    needs: matrix

    runs-on: ubuntu-latest

    name: 'Dockerfile.${{ matrix.configuration }}'

    strategy:
      matrix: 
        configuration: ${{ fromJson(needs.matrix.outputs.configurations) }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: 'Generate Dockerfile'
        working-directory: scripts
        run: php generate.php ${{ matrix.configuration }}

      - name: 'Upload Dockerfile'
        uses: actions/upload-artifact@v3
        with:
          name: Dockerfile.${{ matrix.configuration }}
          path: Dockerfile

      - name: 'Setup Docker buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Docker registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 'Extract Docker metadata'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sander0542/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.configuration }}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
