name: 'Laravel'

on:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
    branches: [ main ]
    paths:
      - 'laravel/**'
      - 'scripts/**'
      - '.github/workflows/laravel.yml'
  push:
    branches: [ main ]
    paths:
      - 'laravel/**'
      - 'scripts/**'
      - '.github/workflows/laravel.yml'

jobs:
  laravel-docker-builder:
      uses: ./.github/workflows/docker-builder.yml
      with:
        WORKDIR: laravel
        IMAGE_NAME: devcontainer-laravel