name: 'Docker'

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ main ]
    paths:
      - 'laravel/**'
      - '.github/workflows/**'

env:
  WORKDIR: laravel

jobs:
  matrix:
    runs-on: ubuntu-latest

    name: 'Matrix'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Load configurations'
        id: configurations
        working-directory: ${{ env.WORKDIR }}/scripts
        run: echo "::set-output name=configurations::$(./configurations.sh)"

    outputs:
      configurations: ${{ steps.configurations.outputs.configurations }}

  dockerfile:
    needs: matrix

    runs-on: ubuntu-latest

    name: 'Dockerfile.${{ matrix.configuration }}'

    strategy:
      matrix: 
        configuration: ${{ fromJson(needs.matrix.outputs.configurations) }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Store repo name and owner in lower case
        shell: bash
        run: echo "LOWER_CASE_REPO_NAME=$(echo ${GITHUB_REPOSITORY} | tr /A-Z/ /a-z/)" >> $GITHUB_ENV

      - name: 'Generate Dockerfile'
        working-directory: ${{ env.WORKDIR }}/scripts
        run: ./generate.sh ${{ matrix.configuration }}

      - name: 'Upload Dockerfile arguments'
        uses: actions/upload-artifact@v3
        with:
          name: env.${{ matrix.configuration }}
          path: ${{ env.WORKDIR }}/env.${{ matrix.configuration }}
          if-no-files-found: error

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Setup Docker buildx'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Extract Docker metadata'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.LOWER_CASE_REPO_NAME }}
          tags: |
            type=raw,value=${{ matrix.configuration }}

      - name: Read build-args file
        id: build-args
        run: echo "BUILD_ARGS=$(cat ${{env.WORKDIR}}/env.${{matrix.configuration}})" >> $GITHUB_ENV

      - name: Echo build args env
        run: echo ${{env.BUILD_ARGS}}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/arm64,linux/amd64
          context: ${{ env.WORKDIR }}
          file: ${{ env.WORKDIR }}/templates/Dockerfile
          # Only releases or pushes to development or main branch
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use env.${{ matrix.configuration }} as list
          build-args: ${{ fromJson(env.BUILD_ARGS) }}
          # Use GitHub Actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
