name: 'Typescript'

on:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
    branches: [ main ]
    paths:
      - 'typescript/**'
      - 'scripts/**'
      - '.github/workflows/typescript.yml'
  push:
    branches: [ main ]
    paths:
      - 'typescript/**'
      - 'scripts/**'
      - '.github/workflows/typescript.yml'

jobs:
  typescript-docker-builder:
      uses: ./.github/workflows/docker-builder.yml
      with:
        WORKDIR: typescript
        IMAGE_NAME: devcontainer-typescript
